Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/08/2026
Var
   VALOR: INTEIRO


Inicio

   para valor de 1 ate 5 faca
      valor<- valor * 2
      escreval("seu valor ao quadrado È:", valor)
   fimpara


Fimalgoritmo